- Cargo.lock
- Cargo.toml
- src/cli/error.rs
- src/lib.rs
- Adds `err-derive` as a dependency
- Implements `error::Error` for `gptman::Error`
- Also eliminates the need for a manual `fmt::Display` impl
Necessary for a library that I'm working on, which needs to be able to handle this library's error type as an error type.
> Impl Error for gptman::Error

- src/lib.rs
Fail with `InvalidPartitionBoundaries` if any partition starts before `first_usable_lba`, ends after `last_usable_lba`, ends before it starts, or overlaps with another partition.
Also fix one incorrect test and one bug found by the new checks.
> Check partition boundaries in GPT.write_into()

- Cargo.toml
The Fedora RPM specfile runs the tests after building the crate, and some of these fail without the fixtures.
Fixes: 4a9e304aaa5e ("Change licensing to MIT OR Apache-2.0")
> Include test fixtures in packaged crate

- .github/workflows/main.yml
- .github/workflows/pr.yml
- Cargo.lock
- Cargo.toml
- src/cli/commands.rs
- src/cli/main.rs
- src/cli/opt.rs
- src/cli/types.rs
- src/lib.rs
- src/linux.rs
I'm switching from err-derive to thiserror because the developer of err-derive is soft deprecating err-derive. You can see it there: https://gitlab.com/torkleyy/err-derive/-/releases
This will probably require a bump in the major as I'm not sure the API of error will stay the same.
I would really love to have a review :heart: maybe @bgilbert or @mmstick can help? :pray: It's very small!
> Switch to thiserror & update dependencies

- Cargo.toml
The library itself doesn't need it.
> Depend on count-zeroes only for cli feature

- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- Cargo.toml
- README.md
Using gptman as a library appears to be the common case.
This is a breaking change, of course.
xref https://github.com/cecton/gptman/pull/77#issuecomment-1124573550
> cargo: Disable CLI by default

- Cargo.lock
- Cargo.toml
- src/cli/commands.rs
- src/cli/main.rs
- src/cli/opt.rs
structopt development has moved into clap.
This enables color help by default, unlike in structopt.  It also changes the `--help` output to group flags with other options.
The gptman `-o` option still allows multiple occurrences (`-o Device -o Sectors`) and multiple delimited values (`-o Device,Sectors`), but due to changes in clap defaults, no longer allows multiple values (`-o Device Sectors`).  The latter syntax is weird (e.g. it precludes `gptman -l -o Device /dev/loop0`, with the device path at the end), so I've left it disabled.
> Replace structopt with clap 3.1

- .github/dependabot.yml
- .github/workflows/update.yml
Disable Dependabot; it's too noisy.  Instead, run `cargo update` once a month and submit a PR.
This won't notice `nix` minor version bumps, unfortunately, and neither does deps.rs (I guess because it's an arch-specific dependency?).  And we probably don't want to declare compatibility with `nix` `>= 0.22, < 1`, since we can't promise that.  I don't have a suggestion here, but I'm okay with leaving that problem unresolved for now.
Sample PR in https://github.com/bgilbert/gptman/pull/4.
> Add monthly workflow to update dependencies

- Cargo.lock
- Cargo.toml
We're compatible with 0.24.
Moving to separate PR, since this isn't really related to #89.
> cargo: Widen nix dependency range

- .github/workflows/update.yml
In newly-created GitHub organizations, `GITHUB_TOKEN` defaults to read-only permissions even for jobs that aren't running from a fork :tada:.  Explicitly specify the access we need.
> workflows: Fix permissions of `cargo update` workflow

- src/lib.rs
> Make Error type non_exhaustive so the API can be stabilized better

- .github/workflows/release.yml
We need this to fix up the broken 1.0.0 release workflow.
> workflows: Temporarily allow running release workflow manually

- .github/workflows/release.yml
We need this to create a release and upload assets, now that the `GITHUB_TOKEN` only grants read access by default.
Also revert #98 now that the release is complete.
> workflows: Add permission to write repo contents

- src/cli/commands.rs
- src/cli/error.rs
@cecton, there's one other lint, and I'm not 100% sure whether the behavior is intentional.  Could you take a look?
> cli: fix clippy 1.63.0 lints

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/cli/opt.rs
Specify `next_display_order = None` to keep the option list sorted in `--help`.
Pretend to continue supporting clap 3 in Cargo.toml so cargo < 1.60 won't fail when building with the CLI disabled.  Delete `Cargo.lock` in MSRV CI jobs for the same reason.
> cli: update to clap 4

- Cargo.toml
> Allow a wider version range for nix.

- src/cli/commands.rs
- src/lib.rs
We're using gptman to build a bootable disk image, that needs to boot on both BIOS and UEFI systems. We've found that some legacy BIOS systems don't consider a disk to be bootable unless the bootable flag is set on the [PMBR](https://www.rodsbooks.com/gdisk/bios.html).
This change is an API break, if you'd prefer to add a separate function or prevent an API break some other way, let me know!
> feat: flag to create pmbr marked as bootable

- src/lib.rs
While testing a new build of our image, we found that it didn't boot in UEFI mode on a Lenovo M700 and tracked it down to this. I think it makes sense to call out this caveat in the rustdoc.
> docs: document that pmbr shouldn't be used unless nedded

- src/linux.rs
This PR will fix the `get_sector_size` function returning `ENOTTY` on the MIPS64 architecture.
> fix: fix get sector size on mips64

- .github/workflows/rust.yml
- Cargo.toml
- src/lib.rs
- **Update bincode to 2.0.1**
- **Update nix dependency**
> Update dependencies bincode and nix
